CREATE TABLE solarman_inverter_data (
    time TIMESTAMPTZ NOT NULL,
    plant_id INT NOT NULL,
    device_id INT NOT NULL,
    operating_state INT,
    fault1 INT,
    fault2 INT,
    fault3 INT,
    fault4 INT,
    fault5 INT,
    solar_voltage_pv1 FLOAT,
    solar_current_pv1 FLOAT,
    solar_voltage_pv2 FLOAT,
    solar_current_pv2 FLOAT,
    solar_power_pv1 FLOAT,
    solar_power_pv2 FLOAT,
    output_power_active FLOAT,
    output_power_reactive FLOAT,
    grid_freq_frequency FLOAT,
    output_voltage_l1 FLOAT,
    output_current_l1 FLOAT,
    output_voltage_l2 FLOAT,
    output_current_l2 FLOAT,
    output_voltage_l3 FLOAT,
    output_current_l3 FLOAT,
    solar_production_total FLOAT,
    solar_time_total FLOAT,
    solar_production_today FLOAT,
    solar_time_today FLOAT,
    inverter_temp_module FLOAT,
    inverter_temp_inner FLOAT,
    inverter_voltage_bus FLOAT,
    inverter_voltage_pv1_voltage_sample FLOAT,
    inverter_current_pv1_current_sample FLOAT,
    inverter_countdown_time FLOAT,
    inverter_alert_message INT,
    input_mode INT,
    communication_board_inner_message INT,
    inverter_insulation_pv1 FLOAT,
    inverter_insulation_pv2 FLOAT,
    cathode_insulation_impedance FLOAT,
    country_code INT,
    UNIQUE (time, plant_id, device_id)
);

SELECT CREATE_HYPERTABLE('solarman_inverter_data', BY_RANGE('time'));
